import { SignInButton, useUser } from "@clerk/nextjs";
import Head from "next/head";
import Image from "next/image";
import PostWizzard from "~/components/PostWizzard";
import { type RouterOutputs, api } from "~/utils/api";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";

dayjs.extend(relativeTime);

type PostWithUser = RouterOutputs["post"]["getAll"][number];
const PostView = ({ postAndAuthor }: { postAndAuthor: PostWithUser }) => {
  const { post, author } = postAndAuthor;
  return (
    <div
      key={post.id}
      className="flex items-center gap-4 border-b border-slate-400 p-4"
    >
      <Image
        className="rounded-full"
        src={author.profileImageUrl}
        alt="Profile image"
        width={56}
        height={56}
      />
      <div className="flex flex-col text-slate-400">
        <div className="flex gap-3 ">
          <span className="font-bold">{`@${author.username}`}</span>
          <span>{`${dayjs(post.createdAt).fromNow()}...`}</span>
        </div>
        <span>{post.content}</span>
      </div>
    </div>
  );
};

export default function Home() {
  const user = useUser();
  const { data, isLoading } = api.post.getAll.useQuery();
  if (isLoading) {
    return <div>Loading....</div>;
  }
  if (!data) {
    return <div>Something went wrong...</div>;
  }

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex  h-screen justify-center">
        <div className="w-full border-x border-slate-400 md:max-w-2xl">
          <div className="flex border-b border-slate-400 p-4">
            {user.isSignedIn ? (
              <PostWizzard />
            ) : (
              <div className="flex justify-center">
                <SignInButton>
                  <button>Sign In with clerk</button>
                </SignInButton>
              </div>
            )}
          </div>
          <div>
            {data.map((postData) => (
              <PostView postAndAuthor={postData} key={postData.post.id} />
            ))}
          </div>
        </div>
      </main>
    </>
  );
}
